name: 'Sync wiki to a branch'
description: 'Synchronize wiki updates with a branch in the repository'

inputs:
  branch:
    description: 'The name of the repository branch that should track the wiki'
    default: 'wiki'
    required: true
  github_token:
    description: 'A GitHub token with permissions to read the wiki and push to the named branch. You will have to create one. It's advisable to create one narrowly scoped to the specific repository you're setting this up for, with only content:read/write permissions'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TARGET_BRANCH: ${{ inputs.branch }}
    TOKEN: ${{ inputs.github_token }}