name: 'Sync wiki to a branch'
description: 'Synchronize wiki updates with a branch in the repository'

inputs:
  branch:
    description: 'The name of the repository branch that should track the wiki'
    default: 'wiki'
    required: true
  github_token:
    description: 'A GitHub token with permissions to read the wiki and push to the named branch'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TARGET_BRANCH: ${{ inputs.branch }}